services:
  - type: worker
    name: crypto-pro-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/telegram_signal_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8851614042:AAHT5tMOB9-G8k43UbdAjnV9EEX709CuF7o
      - key: TELEGRAM_CHAT_ID
        value: "8782542830"